'use client'

import Image from 'next/image'
import Link from 'next/link'
import { useState } from 'react'
import { ArrowLeft, ArrowRight, Bath, BedDouble, CalendarDays, Heart, MapPin, Menu, Ruler, Share2, X } from 'lucide-react'
import { properties } from '@/lib/properties'
import { PropertyAssistant } from './property-assistant'
import { SiteMobileNav } from './site-mobile-nav'

type Property = (typeof properties)[number]

const nearby = ['ITPL · 8 min', 'Phoenix Marketcity · 12 min', 'Whitefield Metro · 15 min', 'The International School · 10 min']

export function PropertyDetails({ property }: { property: Property }) {
  const [activeImage, setActiveImage] = useState(0)
  const gallery = [property.image, `${property.image}&sat=-10`, `${property.image}&con=1`, `${property.image}&blend=ffffff`]
  const [bhk, area] = property.details.split(' · ')
  const bathrooms = bhk.startsWith('4') ? '4 Bathrooms' : bhk.startsWith('3') ? '3 Bathrooms' : '2 Bathrooms'

  return <div className="min-h-screen bg-white text-[#111111]">
    <header className="sticky top-0 z-40 border-b border-[#e5e5e5] bg-white"><div className="relative mx-auto flex h-[58px] max-w-[1280px] items-center gap-4 px-4 lg:h-[72px] lg:px-8"><SiteMobileNav /><Link href="/#top" className="flex items-center text-[#0874d1]" aria-label="OneStep Dream Property home"><span className="text-[28px] font-black leading-none tracking-[-0.12em]">odp</span></Link><nav className="hidden flex-1 items-center justify-center gap-8 text-sm text-[#5f6368] lg:flex" aria-label="Main navigation"><Link href="/#top">Home</Link><Link href="/#properties">Buy Flats</Link><Link href="/#properties">Properties</Link><Link href="/#locations">Locations</Link><Link href="/#about">About Us</Link><Link href="/#contact">Contact</Link></nav><Link href="/#contact" className="ml-auto hidden text-sm text-[#5f6368] lg:block">Login / Register</Link><Link href="/#contact" className="rounded-xl border border-[#0874d1] px-3 py-2 text-sm">List Property</Link></div></header>
    <main>
      <div className="mx-auto max-w-[1280px] px-4 pb-16 pt-7 sm:px-6 lg:px-8 lg:pt-10">
        <Link href="/#properties" className="mb-7 inline-flex items-center gap-2 text-sm font-medium text-[#5f6368] hover:text-[#0874d1]"><ArrowLeft data-icon="inline-start" /> Back to properties</Link>
        <div className="grid gap-10 lg:grid-cols-[1.18fr_.82fr] lg:gap-16">
          <section><div className="relative aspect-[1.18/1] overflow-hidden bg-[#edf5fb] sm:aspect-[1.45/1]"><Image src={gallery[activeImage]} alt={`${property.title} interior`} fill priority className="object-cover" sizes="(max-width: 1024px) 100vw, 60vw" /><div className="absolute inset-x-0 bottom-0 flex items-end justify-between bg-gradient-to-t from-black/45 to-transparent p-4 pt-16"><span className="bg-white px-3 py-1 text-[10px] font-semibold uppercase tracking-[0.14em]">{property.status}</span><span className="text-xs font-medium text-white">{activeImage + 1} / {gallery.length}</span></div><button type="button" aria-label="Previous photo" onClick={() => setActiveImage((activeImage + gallery.length - 1) % gallery.length)} className="absolute left-3 top-1/2 flex size-9 -translate-y-1/2 items-center justify-center rounded-full bg-white/90"><ArrowLeft /></button><button type="button" aria-label="Next photo" onClick={() => setActiveImage((activeImage + 1) % gallery.length)} className="absolute right-3 top-1/2 flex size-9 -translate-y-1/2 items-center justify-center rounded-full bg-white/90"><ArrowRight /></button></div><div className="mt-3 grid grid-cols-4 gap-2">{gallery.map((image, index) => <button type="button" key={image} onClick={() => setActiveImage(index)} className={`relative aspect-[1.4/1] overflow-hidden ${activeImage === index ? 'ring-2 ring-[#0874d1] ring-offset-2' : 'opacity-65 hover:opacity-100'}`} aria-label={`View photo ${index + 1}`}><Image src={image} alt="" fill className="object-cover" sizes="25vw" /></button>)}</div></section>
          <section className="flex flex-col"><div className="flex items-start justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.18em] text-[#0874d1]">{property.status}</p><h1 className="mt-3 text-4xl font-medium leading-[1.02] tracking-[-0.055em] sm:text-5xl">{property.title}</h1><p className="mt-4 flex items-center gap-2 text-sm text-[#5f6368]"><MapPin className="size-4 text-[#0874d1]" /> {property.location}</p></div><button type="button" aria-label="Save property" className="flex size-10 shrink-0 items-center justify-center rounded-full border border-[#dce5eb] hover:bg-[#f5faff]"><Heart /></button></div><div className="mt-8 border-y border-[#e5e5e5] py-5"><p className="text-xs uppercase tracking-[0.14em] text-[#5f6368]">Starting price</p><p className="mt-1 text-3xl font-semibold tracking-[-0.04em] text-[#0874d1]">{property.price}</p></div><div className="grid grid-cols-3 gap-3 border-b border-[#e5e5e5] py-5"><div><BedDouble className="mb-2 size-5 text-[#0874d1]" /><p className="text-sm font-semibold">{bhk}</p><p className="text-xs text-[#5f6368]">Bedrooms</p></div><div><Bath className="mb-2 size-5 text-[#0874d1]" /><p className="text-sm font-semibold">{bathrooms.replace(' Bathrooms', '')}</p><p className="text-xs text-[#5f6368]">Bathrooms</p></div><div><Ruler className="mb-2 size-5 text-[#0874d1]" /><p className="text-sm font-semibold">{area.replace(' sq ft', '')}</p><p className="text-xs text-[#5f6368]">Sq ft</p></div></div><Link href={`/properties/${properties.indexOf(property)}/appointment`} className="mt-7 flex h-14 items-center justify-center gap-2 rounded-xl bg-[#0874d1] px-5 text-sm font-semibold text-white shadow-[0_10px_24px_rgba(8,116,209,.2)] transition hover:bg-[#0667bb]"><CalendarDays data-icon="inline-start" /> Book an Appointment</Link><button type="button" className="mt-3 flex h-12 items-center justify-center gap-2 rounded-xl border border-[#b9d5e8] text-sm font-semibold"><Share2 data-icon="inline-start" /> Share property</button><p className="mt-4 text-center text-xs text-[#77828b]">A property advisor will help you choose a convenient time.</p></section>
        </div>
        <div className="mt-16 grid gap-12 border-t border-[#e5e5e5] pt-10 lg:grid-cols-[1.25fr_.75fr]"><section><p className="text-[11px] font-semibold uppercase tracking-[0.2em] text-[#5f6368]">About this property</p><h2 className="mt-3 text-3xl font-medium tracking-[-0.04em]">A considered home in {property.location.split(',')[0]}.</h2><p className="mt-5 max-w-2xl text-[15px] leading-7 text-[#5f6368]">{property.title} brings together generous spaces, thoughtful finishes, and easy access to the everyday places that make Bengaluru feel like home. Explore a well-planned residence designed for comfortable living and confident long-term value.</p></section><section><p className="text-[11px] font-semibold uppercase tracking-[0.2em] text-[#5f6368]">Nearby locations</p><div className="mt-4 divide-y divide-[#e5e5e5] border-y border-[#e5e5e5]">{nearby.map((place) => <div key={place} className="flex items-center justify-between py-3 text-sm"><span>{place.split(' · ')[0]}</span><span className="text-xs text-[#5f6368]">{place.split(' · ')[1]}</span></div>)}</div></section></div>
      </div>
    </main>
    <footer className="border-t border-[#0874d1] bg-[#0874d1] text-white"><div className="mx-auto flex max-w-[1280px] flex-col gap-4 px-5 py-8 text-sm sm:flex-row sm:items-center sm:justify-between lg:px-8"><Link href="/#top" className="text-[28px] font-black leading-none tracking-[-0.12em]">odp</Link><div className="flex gap-5"><Link href="/#properties">Properties</Link><Link href="/#locations">Locations</Link><Link href="/#contact">Contact</Link></div><span className="text-white/75">© 2026 OneStep Dream Property</span></div></footer>
    <PropertyAssistant />
  </div>
}
